#brew analytics off

tap "azure/kubelogin"
tap "felixkratz/formulae"
tap "koekeishiya/formulae"
tap "mutagen-io/mutagen"
tap "xorpse/formulae"
tap "yt-dlp/taps"

brew "age"
brew "aria2"
brew "aspell"
brew "autoconf"
brew "bash"
brew "bat"
brew "glib"
brew "binutils"
brew "btop"
brew "cmake"
brew "coreutils"
brew "flac"
brew "e2fsprogs"
brew "fastfetch"
brew "fd"
brew "gnutls"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "glab"
brew "gnu-sed"
brew "gnu-tar"
brew "helm@3"
brew "hexyl"
brew "htop"
brew "hwatch"
brew "imagemagick"
brew "jq"
brew "kubecolor"
brew "kubernetes-cli"
brew "kubectx"
brew "llvm"
brew "mas"
brew "midnight-commander"
brew "moreutils"
brew "mtr"
brew "neovim"
brew "nmap"
brew "p7zip"
brew "pbzip2"
brew "php"
brew "pngcrush"
brew "pstree"
brew "pv"
brew "python@3.14"
brew "restic"
brew "ripgrep"
brew "rsync"
brew "screen"
brew "scriptisto"
brew "shellcheck"
brew "shfmt"
brew "sops"
brew "sshpass"
brew "stow"
brew "texlive"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yq"
brew "yt-dlp", args: ["HEAD"]
brew "zsh"
brew "zoxide"
brew "watson"
brew "node"
brew "azure/kubelogin/kubelogin"
brew "felixkratz/formulae/borders"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
brew "mutagen-io/mutagen/mutagen"
brew "ansible"
brew "clang-format"
brew "go"
brew "just"
brew "kondo"
brew "nvm"
brew "oxipng"
brew "pandoc"
brew "rust-analyzer"
brew "tokei"
brew "typescript-language-server"
brew "uv"
brew "worktrunk"
brew "yazi"

cask "1password"
cask "alfred"
cask "appcleaner"
cask "bartender"
cask "discord"
cask "font-dejavu"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "hammerspoon"
cask "karabiner-elements"
cask "keyboard-cleaner"
cask "libreoffice"
cask "obs"
cask "orbstack"
cask "raspberry-pi-imager"
cask "signal"
cask "slack"
cask "subler"
cask "tower"
cask "transmit"
cask "utm"
cask "vlc"
cask "ghostty"
cask "wireshark"
cask "zerotier-one"
cask "zoom"
cask "handbrake-app"
cask "arc"
cask "istat-menus@6"
cask "affinity-designer"
cask "affinity-photo"
cask "upscayl"
cask "imageoptim"
cask "bambu-studio"
cask "claude"
cask "elgato-control-center"
cask "google-chrome"
cask "handbrake"
cask "obsidian"
cask "rocket"
cask "zen-browser"

mas 'Disk Speed Test', id: 425264550 
mas 'Keynote', id: 409183694 
mas 'Webcam Settings', id: 533696630 
mas 'CopyQueue', id: 711074010 
mas 'Droplr', id: 498672703 
mas 'Windows App', id: 1295203466 
mas 'GarageBand', id: 682658836
mas 'The Unarchiver', id: 425424353 
mas 'Amphetamine', id: 937984704 
mas 'Xcode', id: 497799835 
mas 'Numbers', id: 409203825 
mas 'Pages', id: 409201541 
mas 'Fantastical', id: 975937182 
mas 'Bear', id: 1091189122 
mas 'Creator\'s Best Friend', id: 1524172135 
mas 'Yoink', id: 457622435 
