###_R9E_BASHRC_ENABLE_PROFILING=true
source ~/.zgen/zgen.zsh

_R9E_BASHRC_SOURCE_DEFAULT_ALIASES=false
_R9E_BASHRC_SOURCE_DEFAULT_FUNCTIONS=false

source ~/.colorizer/Library/colorizer.sh

source ~/.r9e-bashrc/src/init.sh

source ~/.autojump/bin/autojump.zsh
fpath=(~/.autojump/bin ${fpath})

if ! zgen saved; then
    zgen save
fi
source "${HOME}/.zgen/init.zsh"

HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=green,fg=white,bold'

# Activate all loaded autocompletions
autoload -U compinit && compinit

archey -c

_vagrant_show_status
